altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  f7c8beaf-9988-41ac-90be-75056fd9460e:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 3d0c21d5-2152-48e8-9ca0-b221aa466ba4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 723b165f-92bb-4612-a13b-44bc412b9862
        userCondition: null
fs: algemeenLogoBrand
handle: algemeenLogoBrand
name: 'Algemeen - Logo & Brand'
sortOrder: 37
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
