altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  80467909-2407-4ba7-a03d-47457784460b:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: b959e4fe-c566-42ec-9d23-565b7922daff
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1a40c0d3-1162-438c-a9e0-245ee978996a
        userCondition: null
fs: contentTakken2024
handle: contentTakken2024
name: 'Content - Takken 2024-2025'
sortOrder: 8
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
