altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  906dd110-9b17-4b33-a838-72330238d53d:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: e27559b4-2889-47ce-9b88-0fb843dbc2cf
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9d7e469f-a81a-4748-9257-a44d96f15b5f
        userCondition: null
fs: homepageSlideshow
handle: homepageSlideshow
name: 'Homepage - Slideshow'
sortOrder: 10
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
