altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  ae3c902f-fdcc-49ab-b9ba-51db8e4abe6a:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 7773d64f-9025-4aa9-af6b-178a31d93c83
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 922c497c-601a-4dc2-a6c6-8b905244b2ad
        userCondition: null
fs: homepageBanners
handle: homepageBanners
name: 'Homepage - Banners'
sortOrder: 11
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
