altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  d5c16f21-c471-4e5b-917a-0df286bbba5e:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 77eb302f-ef35-441c-9c97-0363cc0c05ca
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: dc016e53-73ea-40dd-8fd8-7126c5087229
        userCondition: null
fs: icons
handle: icons
name: 'Site Icons'
sortOrder: 3
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
