altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  bd787cd9-2c63-4b3d-82c9-144027edf86e:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 948d24ab-333a-4956-a65a-4fa1445fcea9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 01244267-396c-4a27-b61d-30f1c8696e11
        userCondition: null
fs: kalenderKampen
handle: kalenderKampen
name: 'Kalender - Kampen'
sortOrder: 33
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
