altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  1e23ec4b-d481-40da-b63b-b4678bad337f:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 2576333e-08a9-4622-8b36-e54ab5ec35f3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 14f25195-d2e1-45c1-ad85-863886c9c798
        userCondition: null
fs: kalenderEvenementen
handle: kalenderEvenementen
name: 'Kalender - Evenementen'
sortOrder: 31
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
