altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  5f253ff5-a97f-4b51-9696-8c00066d453c:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: d9d654a5-7ad1-40d1-9d15-081abc13acb4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3cac106e-6fcb-4f53-80f4-c5f5866377aa
        userCondition: null
fs: meerNieuwsberichten
handle: meerNieuwsberichten
name: 'Meer - Nieuwsberichten'
sortOrder: 34
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
