altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  840e699b-4faa-414e-911d-e9603b4a10dd:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 2e56d724-6410-435c-8ad6-91291cf3444c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4aeb115f-a49d-4fa2-8eac-1b135f2c52e5
        userCondition: null
fs: overGeschiedenis
handle: overGeschiedenis
name: 'Over - Geschiedenis'
sortOrder: 29
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
