altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  020386e1-eb51-4ae1-9fbd-ca733e42bda7:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 0461814a-2a41-4340-a23a-273f2aaf5c55
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6eaa247e-0152-4df9-96e9-5e03c22b26e9
        userCondition: null
fs: takkenJongverkenners
handle: takkenJongverkenners
name: 'Takken - Jongverkenners'
sortOrder: 15
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
