altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  b286e05e-582e-4de6-9272-9d41947c867c:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 19ee7b4a-ec51-4c24-b91a-438e6f674572
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3580ec4e-264a-4c62-a25e-83866d4d0129
        userCondition: null
fs: takkenVoortrekkers
handle: takkenVoortrekkers
name: 'Takken - Voortrekkers'
sortOrder: 17
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
