altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  33dc7128-31c7-4860-b802-1b6399c353ca:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 88c176f3-bec4-4930-9489-0f9476d66586
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 419b21c5-b4cb-4873-bc29-f3e910954220
        userCondition: null
fs: thilalaEvenementen
handle: thilalaEvenementen
name: 'Thilala - Evenementen'
sortOrder: 24
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
