altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  d77f831f-9be5-4a1f-99b1-00beffcebb6e:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 156733e1-fcc9-446a-833d-873f36f4fd43
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a5d8fe92-076d-4fb2-9683-8bbd740fc14f
        userCondition: null
fs: thilalaFotoArchief
handle: thilalaFotoArchief
name: 'Thilala - Foto Archief'
sortOrder: 25
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
