altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  e7103c53-baed-4b49-ba1f-b1c63d30222f:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 5dbdc5e8-5e01-47b6-9863-27165588b70d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 345114b8-51e0-4f87-abe6-045bd3ddc00b
        userCondition: null
fs: uiIcons
handle: uiIcons
name: 'UI - Icons'
sortOrder: 7
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
