altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  ecffc28b-bc34-43a7-8acb-76dd7f21c7a9:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 42cc830b-fafb-4c4b-bb19-9905a0a95fbb
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 64df8346-abde-48c0-86cb-15f22e15eb0c
        userCondition: null
fs: verhuurTenten
handle: verhuurTenten
name: 'Verhuur - Tenten'
sortOrder: 21
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
